### ISSUE TITLE
Config change detection and hooks

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-core#11]
In another project we use a similar approach to configuration to dictate sites that must exist and some settings they have. This feature also detects changes in the config and provides hooks for responding to those changes - think activation / deactivation / migration steps.

The core module is the ideal place to handle a feature like this so any platform code or project code can respond to those changes.

For example, a site is added to the property specified in #8 - the CMS module could ensure that the site exists.

**Comment by jennybeaumont** [comment]
Closing as would do if we had a team of 100 (wont do)
