### ISSUE TITLE
About page displays incorrect version for Privacy module

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-core#121]
Steps to reproduce:
1. Switch all packages to v6-branch: `composer run module 'git checkout v6-branch'`
2. Confirm that the `privacy` module is on the correct branch: `cd packages/privacy && git branch --show-current`
3. Start the local server: `composer server start`
4. Go to the Altis About page: `wp-admin/about.php`
5. The Privacy module displays `dev-master` instead of `dev-v6-branch`

![Screen Shot 2021-01-11 at 2 19 50 PM](https://user-images.githubusercontent.com/991511/104240677-b0ad6000-5419-11eb-9e88-5ab0f7bb112b.png)

Acceptance criteria:

- [ ] Privacy module should display the correct version

**Note:** I'm not sure if this is related to the Privacy module being a new addition and it will work itself out but it seems odd/not right...

**Comment by rmccue** [comment]
I think this should sort itself out after release; it's from the Composer lock file, which in production will have an actual version like `6.0.0`.

**Comment by jazzsequence** [comment]
Thanks for confirming @rmccue. I'll assign it to myself and make sure to check it and close this ticket out after release if it's  no longer valid.

**Comment by jennybeaumont** [comment]
Closing as possible future bug
