### ISSUE TITLE
Throw Exception on invalid config

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-core#21]
I've noticed if you have an error in your config, we don't `die`, and if that goes unnoticed, it's very confusing! I think we should a big bad red error for this!

-------------

Acceptance criteria:

- [ ] Change `E_USER_WARNING` to `E_USER_ERROR` in `get_json_file_contents_as_array()` on line 123
- [ ] Add text to the error message before `json_last_error_msg()` saying "`composer.json` could not be parsed\\n"
- [ ] Validate module names under the modules property against registered modules and allow unknown modules if they have an `entrypoint` property, trigger an error if invalid module found
- [ ] Check module names against top level config properties eg. `extra.altis.<module>` and trigger an error if a module name is found with instructions to move it under `extra.altis.modules.<module>`
- [ ] On local environments instead of just triggering an error throw an exception with the same error message

https://github.com/humanmade/altis-core/blob/f0d4e1a1230a149d6c84c99756657cbf7bdcdd71/inc/namespace.php#L119-L124

Use `Altis\Module::get_all()` to get all registered modules.

Examples of invalid configs:

Unregistered module with no "entrypoint" property:
```json
{
  "extra": {
    "altis": {
      "modules": {
        "enhanced-search": { "enabled": false }
      }
    }
  }
}
```

Registered module config not under "modules" property:
```json
{
  "extra": {
    "altis": {
      "search": { "enabled": false }
    }
  }
}
```

Custom module at top level with "entrypoint" property:
```json
{
  "extra": {
    "altis": {
      "custom-module": { "entrypoint": "path/to/file.php" }
    }
  }
}
```

**Comment by kadamwhite** [comment]
+1, certain kind of errors result in a whitescreen 500 with no indication that it's configuration-related.

**Comment by rmccue** [comment]
Punting to v3 as this will require configuration validation, which is a decent amount of work.

**Comment by roborourke** [comment]
Is this referring to type checking the config or just checking if there's an error decoding the JSON?

**Comment by rmccue** [comment]
I think we can start with just checking the decoding error, and swing back to config validation some time in the future.

(Also, it should be doing `trigger_error` with `E_USER_ERROR`, not `die` or exceptions.)

**Comment by roborourke** [comment]
Cheers, updated original comment with acceptance criteria.

**Comment by roborourke** [comment]
Think we need to show an error / warning if an incorrect module name is used too. So if an unregistered module name is found and it has no `entrypoint` property we should trigger an error.

**Comment by roborourke** [comment]
Actually @rmccue - how about a big bad red error just on local? The main reason not to throw or die is to keep production sites running. Killing local harms no one and helps protect against errors making to production without being noticed.

**Comment by joehoyle** [comment]
Also might be good to detect the module names being used at the top level (i.e. the user forgot to put the `modules` sub-key, which I might have done a few times before!

**Comment by roborourke** [comment]
@joehoyle that's a good shout too, in theory shouldn't conflict with any arbitrary config anyone wants to store at the top level
