### ISSUE TITLE
Consider visual configuration editor

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/altis-core#28]
Looking at #21, managing nested JSON configuring multiple environments is somewhat error-prone. Long-term it could be interesting to provide a visual configuration editor similar to how VS Code has evolved the interface for user and workspace settings:
![image](https://user-images.githubusercontent.com/442115/57857871-000f3900-77be-11e9-8369-7267f0209ece.png)
At minimum directing people to make config changes through an editor would give us a place to validate the shape of the config at the time it is being edited or saved, which would reduce the lag between "make edit" and "see error" which might be experienced if you configure a bunch of things then try to run the site and see an error.

**Comment by roborourke** [comment]
I'd also wondered about defining a schema for the config using JSON schema, however that's a little tricky given the flexibility of it, however if we want to add validation that's going to be necessary anyway and probably the first step towards a visual tool like this.

**Comment by rmccue** [comment]
I've had a play around with this, using [monaco-editor](https://microsoft.github.io/monaco-editor/) (the editor used in VS Code). Here's where I got to:

![Screen Recording 2019-05-21 at 16 40 41](https://user-images.githubusercontent.com/21655/58113260-0867d980-7bed-11e9-89c9-bb9f30ebff31.gif)

There's a bug in the Monaco editor (https://github.com/microsoft/monaco-editor/issues/1294) which means that the autocompletion doesn't currently work, but it will.

This is pretty good bang-for-buck, as we get inline validation, completion, and hinting just by producing a JSON Schema.

We can also use some of the underlying tools ([node-jsonc-parser](https://github.com/microsoft/node-jsonc-parser)) to manipulate the JSON data, so e.g. to change the default theme:
```js
const path = [ 'extra', 'altis', 'modules', 'cms', 'default-theme' ];
const newValue = 'twentynineteen';

const edits = modify( source, path, newValue, { formattingOptions: {} } );
const newSource = applyEdits( source, edits );
```

I don't think we need to go the full pref UI route, but we could provide helpers. For example, here's what Sourcegraph does:

<img width="999" alt="Screen Shot 2019-05-21 at 15 58 02" src="https://user-images.githubusercontent.com/21655/58113599-d145f800-7bed-11e9-81d5-bf73cda05605.png">

The buttons at the top are used for some common actions in the editor.

**Comment by rmccue** [comment]
Monaco is unfortunately pretty buggy, _but_ I discovered [react-jsonschema-form](https://mozilla-services.github.io/react-jsonschema-form/) by Mozilla which looks promising.

Key to all of these is codifying what our configuration looks like, which is best done via JSON Schema I think. We'll likely need to change the signature of module registration (https://github.com/humanmade/platform-dev/issues/367) to do this nicely.

**Comment by rmccue** [comment]
Experimenting with react-jsonschema-form:

<img width="597" alt="Screen Shot 2019-06-03 at 12 50 26" src="https://user-images.githubusercontent.com/21655/58799851-3f32ec00-85fe-11e9-9ac0-a0c36ce94584.png">

Per-site configuration may not be supported here, as there's no real way to describe this via JSON Schema, and [react-jsonschema-form doesn't support `additionalItems`](https://react-jsonschema-form.readthedocs.io/en/latest/#json-schema-supporting-status). We may be able to do this by calling `get_sites()` and providing a key for each site, _but_ it's too early. Possibly an extra option or callback to provide [uiSchema](https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/) might be useful too.

**Comment by roborourke** [comment]
With regards to changing the `register_module()` function this would just mean replacing the `$default_settings` parameter with the `$schema` as that will be the place to define defaults.

**Comment by rmccue** [comment]
Closing this out; not worth the effort for now, but we might want to reconsider in the future once we have a configuration framework in place.
