### ISSUE TITLE
Warning:  Use of undefined constant HM_ENV_REGION

### ISSUE THREAD

**Issue by fklein-lu** [humanmade/altis-core#31]
Needs a `defined()` check: https://github.com/humanmade/altis-core/blob/master/inc/namespace.php#L130

**Comment by roborourke** [comment]
@joehoyle any thoughts on the ideal way to set this for local envs? Could default to `us-east-1`, or a string like `not-needed` as set in the local-server module for S3 Uploads.

**Comment by joehoyle** [comment]
Yeah anything like that is fine, I think the env module (chassis I guess in this case) though we responsible for setting that.

**Comment by roborourke** [comment]
@joehoyle it doesn't look like it's set anywhere in `local-server` either. I'll add issues to both of those repos.

**Comment by joehoyle** [comment]
@roborourke rather than this approach, I ended up taking a different route in https://github.com/humanmade/altis-core/pull/40 which I think is a lot more natural, and means we don't need to define this constant in the local servers.
