### ISSUE TITLE
Global media site created despite not enabled

### ISSUE THREAD

**Issue by mattheu** [humanmade/altis-core#336]
I am migrating a site to Altis v8. 

When I run `wp altis migrate` the global media repository site is created. However I have set the following in my `composer.json`, so I would not expect to see the site created. 

```
"altis": {
	"modules": {
	"workflow": {
		"publication-checklist": false
	},
	"media": {
		"global-media-library": false
	},
},
```

It looks like there are no checks to see if this feature is enabled in the migration command, which is where the site is created. 

See: https://github.com/humanmade/altis-core/blob/master/inc/global_content/namespace.php#L107

**Comment by roborourke** [comment]
That’s intentional behaviour, this is the global content repository rather than specifically global media. It’s a feature that other shared content can be built on top of. Media is one option we provide out of the box so far.

**Comment by rmccue** [comment]
Closing, not a bug.
