### ISSUE TITLE
Unable to filter `altis.config` in `/.config/load.php`.

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/altis-core#37]
The `altis.config` filter fires prior to project specific config files being loaded in `/.config/load.php`. This prevents the ability to alter the config via PHP.

Steps to reproduce:

1. Create an Altis project
2. Add the following to your `/.config/load.php` file:
  ```php
  add_filter(
	'altis.config',
	function( $config ) {
		var_dump( 'config', $config );
		exit;
		return $config;
	}
  );
  ```
3. Witness Altis loading despite the `exit`.

**Comment by roborourke** [comment]
This filter only works within a module in case you needed to add some advanced config merging logic for example. I'm not sure we want to change that but can you elaborate on your use-case a bit?

**Comment by peterwilsoncc** [comment]
This came up on what I'm dubbing Altish, running the code base on an everyday server rather than with all the defaults available on the full DXP.

The use case I was using it for was that most modules need to be disabled by default so modifying the config via PHP becomes a clearer and less error prone approach. Any new modules need to be off by default.

The work around I used was to autoload `/.config/load.php` and gate file with a `function_exists()` call. 

https://github.com/peterwilsoncc/doitlive.peterwilson.cc/blob/1a7090fb4b15ef86416cd69ee653a0ab8c4c3a07/.config/load.php#L10-L34

As this doesn't affect Altis proper, feel free to close the ticket as out of scope.

**Comment by roborourke** [comment]
Oh cool! Well we should perhaps revisit the default enabled settings for some modules. I think another approach would be to create your own custom module, there's a guide for that in the docs. Autoloading that file has the same basic effect as making it a module so if that works for you then 👍

**Comment by joehoyle** [comment]
I think this actually could be quite a common use case. If you want to do procedural modifications of the config, you I think should able to do this via the .config/load.php file. Would this just be the case of changing the order of including `.config/load.php`? Though I guess the inverse it true where you might want to _read_ from the existing config in your `load.php`.

Perhaps a `.config/pre-load.php` would do the trick :P
