### ISSUE TITLE
Add docs on CMS privacy page feature

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-core#47]
WP has a built in privacy page feature including the ability for a user to request all their data. We should document how to implement this and any special additions we add to the default behaviour in this module.

**Comment by nathanielks** [comment]
It would also be good to document some new X-Ray filters that [I just added today](https://github.com/humanmade/aws-xray/pull/34): `aws_xray.redact_metadata_keys` and `aws_xray.redact_metadata`.

`aws_xray.redact_metadata_keys` expects an array like:
```php
[
  '$_POST' => [
    'key1',
    'key2',
  ],
  '$_COOKIE' => [
    'key3',
  ],
];
```

Where `key1`, `key2`, `key3` will be transformed to say `REDACTED` in the trace.

Additionally, `aws_xray.redact_metadata` allows the entire `$metadata` variable to be filtered as a function sees fit. I'm happy to write the docs for this, just need to know where whenever it gets drafted!

Scrollback: https://hmn.slack.com/archives/C3CKS8LLR/p1564509725183900

**Comment by roborourke** [comment]
@nathanielks awesome - can you add the docs to this PR? #48 
Or branch off that if it hasn't been merged already.

Also can you think of some keys / metadata we should redact by default? Would be a good feature.
