### ISSUE TITLE
Alphabetize plugin override list

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/altis-core#50]
This list [`inc/composer/class-installer.php#L26`](https://github.com/humanmade/altis-core/blob/master/inc/composer/class-installer.php#L26) of plugins we exclude from normal type-based path determination is not alphabetized, and organizing it could improve ease-of-maintenance going forward.

**Comment by kadamwhite** [comment]
@joehoyle @roborourke Any objection to this?

**Comment by roborourke** [comment]
Nope, good with me :)
