### ISSUE TITLE
Telemetry is still sent to cdn.segment.com when telemetry is disabled

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-core#514]
Steps to reproduce:
1. Visit your user profile editing screen at `wp-admin/profile.php`
2. Ensure the "Opt in to Altis Telemetry" checkbox is unchecked
3. Observe that a JavaScript file is still loaded from `https://cdn.segment.com/analytics.js/v1/<snip>/analytics.min.js`
4. Observe that a request is still sent to `https://api.segment.io/v1/p` with a payload that includes an `anonymousId` parameter that appears to remain static between page loads

No cookies are set for either of these domains, but given the above it appears my usage of Altis is still being tracked by a third party despite my opting out.

**Comment by rmccue** [comment]
We could be clearer about the language, but this is not a bug. The opt-in affects whether any personal data is sent, but telemetry is always sent for product improvement purposes.

**Comment by rmccue** [comment]
Updated description.
