### ISSUE TITLE
About Page Inconsistencies

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-core#56]
<img width="799" alt="Screenshot 2019-10-11 at 17 19 56" src="https://user-images.githubusercontent.com/58855/66667632-5e482700-ec4b-11e9-9d46-fd44c29f5d1d.png">

The Altis About page has 2 tabs, but they have no relation to their contents. e.g. the credits tab has no credits, but instead lists composer packages. The about tab doesn't say anything about Altis and just lists the modules and their versions. The credits tab actually has a sentence about Altis. A graphic would also make this page a little friendlier

Suggestions:

- Put an Altis logo on "Powered by Altis"
- re-align the main/sub headings and the table so they align horizontally better to the left
- Rename the About tab to Modules
- Rename Credits to Packages
- Add an initial Altis tab with a logo and a description of what it is, the paragraph on the credits tab is already most of the way there

**Comment by tomjn** [comment]
It also seems that the credits tab makes a request to the .org API

**Comment by rmccue** [comment]
This is more akin to an app's About page right now, so I don't think we need further detail here. See prior discussions with marketing around this.

Mostly, this is meant to be an info page with some data about the system, it's not meant to be user-facing in the same way WordPress' is.

**Comment by rmccue** [comment]
Closing out as I think this is covered in our previous discussions, sorry for the confusion.
