### ISSUE TITLE
Altis Media 2.0.1 installs Safe SVG to plugins folder.

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/altis-core#60]
humanmade/altis-media 2.0.1 is installing Safe SVG to the plugins folder as PR #52 of Altis Core has not been released.

I don't think `apply_filters()` and related functions are available when the installer runs but if they are, is it possible to add a filter to the plugin list to allow modules to add their own plugins to be installed in the vendor folder?

**Comment by rmccue** [comment]
Looks like the problem here is actually that we shouldn't have backported Safe SVG, as it's meant to be in v3 only.

> I don't think `apply_filters()` and related functions are available when the installer runs but if they are, is it possible to add a filter to the plugin list to allow modules to add their own plugins to be installed in the vendor folder?

Alas, it is not; the Composer installer doesn't run in the WordPress context.

**Comment by rmccue** [comment]
Reverted the v2 change in https://github.com/humanmade/altis-media/pull/47 and released as `altis/media@2.0.2` - installer will be updated in v3 for the actual release.
