### ISSUE TITLE
Coerce module settings to array if boolean set in config

### ISSUE THREAD

**Issue by kucrut** [humanmade/altis-core#63]
If a module configuration is set to a boolean value eg. `false` to turn it off there's a merge error and a warning thrown.

We need to check the type of the value of `$settings` in the following lines:

https://github.com/humanmade/altis-core/blob/f0d4e1a1230a149d6c84c99756657cbf7bdcdd71/inc/namespace.php#L82-L85

If the type is a boolean then the value should be set to:

```php
$settings = [
    'enabled' => settings
];
```

If the type is anything other than a boolean or array then we should trigger a warning using `trigger_error( ..., E_USER_WARNING )` indicating which module settings are broken and then `continue;` the loop.

Acceptance criteria:

- [ ] Setting a module in `composer.json` config to `true` or `false` should not trigger an `array_merge` warning
- [ ] A boolean value set for a module in `composer.json` should be used as the `enabled` setting value

-----------

## Original iisue

Similar to [this issue](https://github.com/humanmade/altis-local-chassis/issues/67), I'm seeing this error from the site's PHP logs:

```
PHP Warning:  array_merge(): Argument #2 is not an array in /chassis/vendor/altis/core/inc/namespace.php on line 83
```

Here's the snippet of the project's composer config:

```json
{
  "extra": {
     "altis": {
      "modules": {
        "media": {
          "smart-media": false,
          "tachyon": false
        },
        "workflow": false,
        "seo": {
          "redirects": false
        },
        "analytics": {
          "native": {
            "experiments": {
              "titles": false
            }
          }
        }
      }
    }
  }
}
```

**Comment by roborourke** [comment]
@kucrut might be the `workflow` setting, you could try using:

```json
{
  "extra": {
     "altis": {
      "modules": {
        "workflow": {
          "enabled": false
        }
      }
    }
  }
}
```

I think we need to make sure we coerce any boolean values here into an array with the boolean as the value of the enabled setting.

**Comment by roborourke** [comment]
Updated the original comment with instructions to fix the bug.

**Comment by kucrut** [comment]
@roborourke Yep, that worked. Thanks!
