### ISSUE TITLE
FIX PHP 8.2 deprecation warnings in Altis v15

### ISSUE THREAD

**Issue by wisyhambolu** [humanmade/altis-core#772]
### Description

Altis on PHP 8.2 has been [reported](https://dev.hmn.md/2023/07/03/php-8-2-not-recommended-for-altis/) to trigger a high number of PHP deprecation warnings in 8.2 which make it very hard to see and diagnose actual issues, we need to fix this to enable clients have better visibility within their log files.

### Acceptance Criteria
- [ ] No PHP deprecation warnings are reported in Altis v15 when running PHP 8.2

**Comment by ferschubert-hm** [comment]
@mikelittle to add more context on this (where the warnings are coming from)

**Comment by mikelittle** [comment]
https://app.zenhub.com/workspaces/vulcan-6284e0dfb386b00c83981426/issues/gh/humanmade/product-dev/1411

**Comment by mikelittle** [comment]
https://app.zenhub.com/workspaces/vulcan-6284e0dfb386b00c83981426/issues/gh/humanmade/product-dev/1411

**Comment by mikelittle** [comment]
https://app.zenhub.com/workspaces/vulcan-6284e0dfb386b00c83981426/issues/gh/humanmade/altis-cloud/785

**Comment by mikelittle** [comment]
https://app.zenhub.com/workspaces/vulcan-6284e0dfb386b00c83981426/issues/gh/humanmade/altis-security/255

**Comment by mikelittle** [comment]
https://app.zenhub.com/workspaces/vulcan-6284e0dfb386b00c83981426/issues/gh/humanmade/altis-security/274

**Comment by mikelittle** [comment]
https://app.zenhub.com/workspaces/vulcan-6284e0dfb386b00c83981426/issues/gh/humanmade/altis-security/275

**Comment by mikelittle** [comment]
https://app.zenhub.com/workspaces/vulcan-6284e0dfb386b00c83981426/issues/gh/humanmade/docker-wordpress-php/182

**Comment by mikelittle** [comment]
@owaincuvelier Do you have any more exampes of PHP 8.2 (or 8.1) warnings and notices that aren't mentioned above?

**Comment by owaincuvelier** [comment]
@mikelittle yeah I've been meaning to create tickets from the report in here: https://humanmade.zendesk.com/agent/tickets/7921 still haven't had time yet. If you can take a look you might be able to see if they've been covered or not?

**Comment by mikelittle** [comment]
That's great. Thanks. I'll take a look.

**Comment by mikelittle** [comment]
https://github.com/humanmade/Cavalcade/issues/123

**Comment by mikelittle** [comment]
These are all the ones I have been able to identify so far. I'll close this ticket now and any more occurrences can have their own tickets.
