### ISSUE TITLE
Support for per site overrides in config

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-core#8]
It's quite likely we may need to account for per site overrides of certain config values, things in the SEO module for example re. setting facebook page ID, twitter URL and so on might be different for individual sites on the network.

My proposal is to use the same approach outlined for per environment overrides, for example:

```json
{
  "extra": {
    "platform": {
       "modules": { "...": "..." },
       "sites": {
         "subsite.example.com": {
           "modules": {
             "...": "..."
           }
         }
       }
    }
  }
}
```

The config would be matched on the keys under `sites` and the current host name. We could quite easily support wildcards or full regex matches too.

**Comment by roborourke** [comment]
Can maybe write this up as an RFC thinking about it...

**Comment by roborourke** [comment]
@tcrsavage per your question about per site overrides - if you have any feedback here's a good place for it. Would the above approach work for you or do you think there needs to be some wildcard / regex style matching support?

**Comment by tcrsavage** [comment]
@roborourke I did some playing around with a similar piece of functionality for a client project  (ping for link)

Main aims there was to:

- Dictate which sites should exist and their associated urls for each environment
- Dictate plugins which should be enabled with no ability to disable outside of code
- Dictate the theme which should enabled with no ability to change theme outside of code 
- Dictate any options which should set with no ability to change theme outside of code 

I think the first one one that list can be ignored in the interests of getting something that works well out of the box. Not having this in place allows for more unnecessary variance between environments, but there are some complexities around adding/deletion of sites via code which maybe we can have a talk about separately.

I think it's very common that you want to share most settings between the same sites, but those sites have different urls depending on the environment, so makes sense that you can define top priority settings to a defined site url. Couple of obvious use cases:

**I have a plugin which I want:**
1 - Enabled on all sites on all environments 
2 - Enabled on one site on all environments
3 - Enabled on one site on one environment

Feels like all this fits, though I would have to define the enabled plugin in 3 or more individual rules for scenario 2 - Not a big issue for most projects but I can see places where this could get messy there are large amounts of site level customisation. Comma separated list might be more useful than regex + clear deterministic prioritisation of overrides in the sites list.

**Comment by roborourke** [comment]
@joehoyle @rmccue noting here that this use-case has already come up on a project whereby a sub site needs require login to be on in production but not for the main site.

I'm gonna spin up an issue for loading require login if a site is not marked as public in the mean time.

**Comment by roborourke** [comment]
Brief update, that use-case mentioned is now handled by setting the site's public option to be on or off.

**Comment by jennybeaumont** [comment]
Closing as we've decided not to go in this direction. Config is focused on global settings, rather than site-specific.
