### ISSUE TITLE
Altis Consent options should be configurable via Altis config

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-core#87]
## Description

All options available for the Altis consent module should be configurable from the `composer.json` file. This means that before including into Altis, we'll need to make sure to check the config and update the options on Altis init.

Some decision should be made about the behavior of the options that defined in the config vs. in the admin. There may be cases where we want to disable any user-facing UI (or disable the user-facing UI with the exception of the privacy and cookie policy pages) but there may also be cases where we just want to define intelligent defaults that can be edited on a site level.

**Comment by jennybeaumont** [comment]
>All options available for the Altis consent module should be configurable from the composer.json file

Why?

**Comment by jazzsequence** [comment]
Ideally to simplify what could be a complicated admin interface, and remove options that are never going to be (or highly unlikely to be) changed.

**Comment by roborourke** [comment]
Is this still relevant? We have some configuration options in the privacy module. I think this issue is from before we had the privacy module.
